name = "auction-engine"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "AUCTION_DB"
database_name = "auction-engine-db"
database_id = "931d6378-238f-4849-919b-f76d083485b7"

[[durable_objects.bindings]]
name = "AUCTION_ROOM"
class_name = "AuctionRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["AuctionRoom"]
