# ==========================================================================
# CRE PROJECT SETTINGS FILE
# ==========================================================================
# Project-level RPC and account settings for CRE CLI targets.

# ==========================================================================
local-simulation:
  rpcs:
    - chain-name: ethereum-testnet-sepolia-base-1
      url: https://sepolia.base.org

# ==========================================================================
base-sepolia:
  cre-cli:
    don-family: "zone-a"
  rpcs:
    - chain-name: ethereum-testnet-sepolia-base-1
      url: https://sepolia.base.org
