[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = false
ffi = false

# Remappings
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@account-abstraction/=lib/account-abstraction/contracts/",
    "@chainlink/contracts/=lib/chainlink/contracts/",
]

# Testing
[profile.default.fuzz]
runs = 256

# Formatting
[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = "long"
multiline_func_header = "attributes_first"
quote_style = "double"
number_underscore = "thousands"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
